// Writes build/vectors.ts: every case of spec/vectors as a literal that must satisfy its op's argument and reply
// types, so the hand-written wire types cannot drift from the core. Run by npm run check, before tsc.

import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

const spec = new URL("../../spec/", import.meta.url)
const out = new URL("../build/vectors.ts", import.meta.url)

/** A JSON file under spec/, its { "$ref": … } objects replaced by what they name. */
function load(path: URL): unknown {
  return resolve(JSON.parse(readFileSync(path, "utf8")))
}

function resolve(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(resolve)
  if (value === null || typeof value !== "object") return value
  const entries = Object.entries(value)
  if (entries.length === 1 && entries[0]?.[0] === "$ref" && typeof entries[0][1] === "string") {
    return load(new URL(entries[0][1], spec))
  }
  return Object.fromEntries(entries.map(([key, inner]) => [key, resolve(inner)]))
}

const lines = [
  "// Generated by scripts/vectors.mts from spec/vectors; do not edit. Every case satisfies its op's types.",
  "",
  'import type { Vector } from "../src/ops.ts"',
  "",
]
for (const family of readdirSync(new URL("vectors/", spec)).sort()) {
  for (const file of readdirSync(new URL(`vectors/${family}/`, spec)).sort()) {
    const literal = JSON.stringify(load(new URL(`vectors/${family}/${file}`, spec)), null, 2)
    lines.push(`// ${family}/${file}`, `;(${literal}) satisfies Vector<${JSON.stringify(family)}>`, "")
  }
}
mkdirSync(new URL("../build/", import.meta.url), { recursive: true })
writeFileSync(out, lines.join("\n"))
console.log(`${fileURLToPath(out)}: ${lines.length} lines`)
