//! TypeScript for authors and apps. In: a `Manifest`; an `Installed` set. Out: `reflex.d.ts` — `Args` as a body
//! receives them, `Config` as it is resolved, and `Context`, `Result` and `Reflex` bound to them, so a body imports
//! the one file beside it and no package — and `evoke.d.ts` — what a decision's `args` carry per installed reflex,
//! for `load<Reflexes>` — as text. Pinned by the vectors, so the CLI and the SDK write identical files.

use std::fmt::Write as _;

use crate::manifest::{Argument, Kind, Manifest, Pick, Source};
use crate::name::OptionKey;
use crate::plan::Installed;

/// What every `reflex.d.ts` ends with: the body's context, result and type, bound to its `Args` and `Config`.
const BODY: &str = "\
/** What the body receives beside its arguments. */
export interface Context {
  /** The input as it was typed. */
  input: string
  config: Config
  /** Aborted at the deadline or on a decline: stop, never guess. */
  signal: AbortSignal
}

/** What the body returns: the text a person reads, and data an app may use. */
export type Result = string | { text: string; data?: unknown }

/** The body: the default export of the file `run` names. */
export type Reflex = (args: Args, context: Context) => Result | Promise<Result>
";

/// `reflex.d.ts`: the arguments a body receives — an option key, a word or its value, a pick's value, `true` for a
/// flag — its config, every value a string, and the body's own type over both.
#[must_use]
pub fn reflex_dts(m: &Manifest) -> String {
    let mut text = String::from("// Generated by evoke check; do not edit.\n\n");
    let args = m.args.iter().map(|(name, argument)| {
        let (ty, optional) = match &argument.kind {
            Kind::Flag => ("true".to_owned(), true),
            Kind::Value { source, optional } => (
                match source {
                    Source::Options(options) => union(options.keys().map(OptionKey::as_str)),
                    Source::Pick(Pick::Number(_) | Pick::Duration(_)) => "number".to_owned(),
                    Source::Vocab(_) | Source::Pick(Pick::Email | Pick::Url | Pick::Quoted) => {
                        "string".to_owned()
                    }
                },
                *optional,
            ),
        };
        Member {
            doc: argument.ask.to_string(),
            name: name.as_str(),
            optional,
            ty,
        }
    });
    // A whole result reaches the body as its source returned it: evoke checks no shape.
    let taken = m.takes.iter().map(|(name, result)| Member {
        doc: format!("The whole result of an earlier step that returns {result}."),
        name: name.as_str(),
        optional: false,
        ty: "unknown".to_owned(),
    });
    interface(&mut text, "Args", "", args.chain(taken));
    text.push('\n');
    let config = m.config.iter().map(|(key, spec)| Member {
        doc: spec.about.to_string(),
        name: key.as_str(),
        optional: false,
        ty: "string".to_owned(),
    });
    interface(&mut text, "Config", "", config);
    text.push('\n');
    text.push_str(BODY);
    text
}

/// `evoke.d.ts`: per installed reflex whose manifest reads, its arguments as a decision carries them — typed
/// values, their shapes declared once above.
#[must_use]
pub fn project_dts(set: &Installed) -> String {
    let mut text = String::from(
        "// Generated by evoke add, update and remove; do not edit.\n\
         // What a decision's args carry, per installed reflex: load<Reflexes> narrows them by reflex.\n\
         \n\
         export type Option<K extends string> = { type: \"option\"; key: K }\n\
         export type Word = { type: \"word\"; word: string; value?: string }\n\
         export type Pick<T extends string, V> = { type: \"pick\"; span: { start: number; end: number; text: string }; value: { type: T; value: V } }\n\
         export type Flag = { type: \"flag\" }\n\
         \n",
    );
    let reflexes: Vec<(&str, &Manifest)> = set
        .reflexes
        .iter()
        .filter_map(|(name, item)| Some((name.as_str(), &item.wording.as_ref().ok()?.manifest)))
        .collect();
    if reflexes.is_empty() {
        text.push_str("export interface Reflexes {}\n");
        return text;
    }
    text.push_str("export interface Reflexes {\n");
    for (name, manifest) in reflexes {
        let _ = writeln!(text, "  {name}: {{");
        for (arg, argument) in &manifest.args {
            member(&mut text, "    ", &carried(argument, arg.as_str()));
        }
        text.push_str("  }\n");
    }
    text.push_str("}\n");
    text
}

/// One member of an interface: its doc line, its name, whether it may be absent, its type.
struct Member<'a> {
    doc: String,
    name: &'a str,
    optional: bool,
    ty: String,
}

/// An argument as a decision carries it: `Option<…>`, `Word`, `Pick<…>` or `Flag`, absent when optional.
fn carried<'a>(argument: &'a Argument, name: &'a str) -> Member<'a> {
    let (ty, optional) = match &argument.kind {
        Kind::Flag => ("Flag".to_owned(), true),
        Kind::Value { source, optional } => (
            match source {
                Source::Options(options) => {
                    format!("Option<{}>", union(options.keys().map(OptionKey::as_str)))
                }
                Source::Vocab(_) => "Word".to_owned(),
                Source::Pick(pick) => {
                    let value = match pick {
                        Pick::Number(_) | Pick::Duration(_) => "number",
                        Pick::Email | Pick::Url | Pick::Quoted => "string",
                    };
                    format!("Pick<{}, {value}>", quoted(pick.recognizer().name()))
                }
            },
            *optional,
        ),
    };
    Member {
        doc: argument.ask.to_string(),
        name,
        optional,
        ty,
    }
}

/// `export interface <name> {}` when empty, else one member per line.
fn interface<'a>(
    text: &mut String,
    name: &str,
    indent: &str,
    members: impl Iterator<Item = Member<'a>>,
) {
    let members: Vec<Member<'a>> = members.collect();
    if members.is_empty() {
        let _ = writeln!(text, "{indent}export interface {name} {{}}");
        return;
    }
    let _ = writeln!(text, "{indent}export interface {name} {{");
    for m in &members {
        member(text, &format!("{indent}  "), m);
    }
    let _ = writeln!(text, "{indent}}}");
}

/// `/** doc */` then `name?: type`.
fn member(text: &mut String, indent: &str, m: &Member<'_>) {
    let _ = writeln!(text, "{indent}/** {} */", m.doc.replace("*/", "*\\/"));
    let mark = if m.optional { "?" } else { "" };
    let _ = writeln!(text, "{indent}{}{mark}: {}", m.name, m.ty);
}

/// `"a" | "b"`: every option key as a string literal type.
fn union<'a>(keys: impl Iterator<Item = &'a str>) -> String {
    keys.map(quoted).collect::<Vec<_>>().join(" | ")
}

fn quoted(text: &str) -> String {
    serde_json::Value::String(text.to_owned()).to_string()
}
