//! What holds of the gate over readings no one wrote, drawn over `spec/fixtures/plan.json` with judgments
//! anywhere in `[0, 1]`: raising the route's or an effect's floor never moves an outcome toward run, and never
//! makes an ask of a call; `read` above `write` is refused; a destructive winner never runs under any gate, or
//! none; the confidence is the weakest judgment; filling any subset of an ask's missing arguments keeps the
//! route and drops exactly their judgments. Generated by proptest and shrunk; a failure's seed lands in
//! `proptest-regressions/`. The `fits` floor is the runner-up's and works the other way: raised, it caps less.

use evoke_core::adapter::{Key, Prob, QuestionId};
use evoke_core::call::Value;
use evoke_core::decide::{Contender, Judgment, Reading, Winner};
use evoke_core::name::{ArgName, LocalName, OptionKey, Word};
use evoke_core::propose::PickValue;
use evoke_core::text::{Clean, Input, Span};
use evoke_core::{Decision, Gate, Judged, Plan, fill, gate};
use indexmap::IndexMap;
use proptest::prelude::*;
use serde_json::Value as Json;

fn plan() -> Plan {
    serde_json::from_str(include_str!("../../../spec/fixtures/plan.json")).unwrap()
}

/// The same plan with `lights` destructive.
fn destructive_plan() -> Plan {
    let mut json: Json =
        serde_json::from_str(include_str!("../../../spec/fixtures/plan.json")).unwrap();
    json["active"]["lights"]["effect"] = Json::from("destructive");
    serde_json::from_value(json).unwrap()
}

fn p(value: f64) -> Prob {
    Prob::new(value).unwrap()
}

fn name(text: &str) -> LocalName {
    LocalName::new(text).unwrap()
}

fn arg(text: &str) -> ArgName {
    ArgName::new(text).unwrap()
}

fn key(text: &str) -> Key {
    Key::new(text).unwrap()
}

fn judgment(question: QuestionId, top: &str, prob: f64) -> Judgment {
    Judgment {
        question,
        top: key(top),
        p: p(prob),
    }
}

/// A pick's value with the span it was read from.
fn pick(input: &str, start: usize, end: usize, value: PickValue) -> Value {
    let input = Input::new(input).unwrap();
    Value::Pick {
        span: Span::of(&input, start, end).unwrap(),
        value,
    }
}

/// What one argument's judgment read: the top key, and the value it settles to when it is not `unstated`.
#[derive(Clone, Debug)]
struct Read {
    top: &'static str,
    value: Option<Value>,
}

fn room() -> impl Strategy<Value = Read> {
    prop_oneof![
        Just(Read {
            top: "den",
            value: Some(Value::Word {
                word: Word::new("den").unwrap(),
                value: None
            })
        }),
        Just(Read {
            top: "office",
            value: Some(Value::Word {
                word: Word::new("office").unwrap(),
                value: None
            })
        }),
        Just(Read {
            top: "unstated",
            value: None
        }),
    ]
}

fn state() -> impl Strategy<Value = Read> {
    prop_oneof![
        Just(Read {
            top: "on",
            value: Some(Value::Option {
                key: OptionKey::new("on").unwrap()
            })
        }),
        Just(Read {
            top: "off",
            value: Some(Value::Option {
                key: OptionKey::new("off").unwrap()
            })
        }),
        Just(Read {
            top: "unstated",
            value: None
        }),
    ]
}

fn brightness() -> impl Strategy<Value = Option<Read>> {
    prop_oneof![
        Just(None),
        Just(Some(Read {
            top: "18-28",
            value: Some(pick(
                "dim the office to 30 percent",
                18,
                28,
                PickValue::Number { value: 30.0 }
            ))
        })),
        Just(Some(Read {
            top: "unstated",
            value: None
        })),
    ]
}

fn duration() -> impl Strategy<Value = Read> {
    prop_oneof![
        Just(Read {
            top: "16-26",
            value: Some(pick(
                "set a timer for 10 minutes",
                16,
                26,
                PickValue::Seconds { value: 600 }
            ))
        }),
        Just(Read {
            top: "unstated",
            value: None
        }),
    ]
}

fn label() -> impl Strategy<Value = Option<Read>> {
    prop_oneof![
        Just(None),
        Just(Some(Read {
            top: "28-32",
            value: Some(pick(
                "timer for 3 minutes called \"eggs\"",
                28,
                32,
                PickValue::Quoted {
                    value: Clean::new("eggs").unwrap()
                }
            ))
        })),
        Just(Some(Read {
            top: "unstated",
            value: None
        })),
    ]
}

/// A probability anywhere in `[0, 1]`, the ends included.
fn prob() -> impl Strategy<Value = f64> {
    prop_oneof![9 => 0.0..=1.0, 1 => Just(0.5), 1 => Just(1.0), 1 => Just(0.0)]
}

/// A reading of the fixture plan: a winner with its route probability, each argument asked judged at any
/// probability, an optional argument perhaps not asked, and a runner-up with or without `fits`.
fn reading() -> impl Strategy<Value = Reading> {
    let lights = (room(), prob(), state(), prob(), brightness(), prob()).prop_map(
        |(room, room_p, state, state_p, brightness, brightness_p)| {
            let mut asked = vec![("room", room, room_p), ("state", state, state_p)];
            if let Some(brightness) = brightness {
                asked.push(("brightness", brightness, brightness_p));
            }
            ("lights", asked)
        },
    );
    let timer =
        (duration(), prob(), label(), prob()).prop_map(|(duration, duration_p, label, label_p)| {
            let mut asked = vec![("duration", duration, duration_p)];
            if let Some(label) = label {
                asked.push(("label", label, label_p));
            }
            ("timer", asked)
        });
    (
        prop_oneof![lights, timer],
        prob(),
        proptest::option::of(prob()),
    )
        .prop_map(|((winner, asked), route, fits)| {
            let winner = name(winner);
            let other = name(if winner.as_str() == "lights" {
                "timer"
            } else {
                "lights"
            });
            let mut judgments = vec![judgment(QuestionId::Route, winner.as_str(), route)];
            let mut args = IndexMap::new();
            for (name, read, prob) in asked {
                judgments.push(judgment(
                    QuestionId::Arg(winner.clone(), arg(name)),
                    read.top,
                    prob,
                ));
                if let Some(value) = read.value {
                    args.insert(arg(name), value);
                }
            }
            let runner_up = Contender {
                reflex: other.clone(),
                route: p((1.0 - route).max(0.0)),
                fits: fits.map(p),
            };
            Reading {
                ranking: vec![
                    Contender {
                        reflex: winner.clone(),
                        route: p(route),
                        fits: None,
                    },
                    runner_up.clone(),
                ],
                judgments,
                winner: Some(Winner {
                    reflex: winner,
                    args,
                    missing: Vec::new(),
                    unconsumed: Vec::new(),
                    runner_up: Some(runner_up),
                }),
            }
        })
}

/// A gate with `read` at or under `write`.
fn a_gate() -> impl Strategy<Value = Gate> {
    (prob(), proptest::option::of(prob()), prob(), prob()).prop_map(|(route, fits, a, b)| {
        Gate::new(p(route), fits.map(p), p(a.min(b)), p(a.max(b))).unwrap()
    })
}

/// The same gate, with the route's and each effect's floor raised by some amount; `fits` as it was.
fn raised(gate: Gate) -> impl Strategy<Value = Gate> {
    (prob(), prob(), prob()).prop_map(move |(route, read, write)| {
        let route = gate.route().get().max(route);
        let read = gate.read().get().max(read);
        let write = gate.write().get().max(write).max(read);
        Gate::new(p(route), gate.fits(), p(read), p(write)).unwrap()
    })
}

/// The outcome's word, for an assertion to name.
fn outcome(decision: &Decision) -> &'static str {
    match decision {
        Decision::Abstain { .. } => "abstain",
        Decision::Run { .. } => "run",
        Decision::Confirm { .. } => "confirm",
        Decision::Ask { .. } => "ask",
    }
}

/// The reflex a decision is about, and the judgments it rests on.
fn rests_on(decision: &Decision) -> Option<(&LocalName, Vec<QuestionId>)> {
    let (reflex, judged) = match decision {
        Decision::Abstain { .. } => return None,
        Decision::Run { chosen } | Decision::Confirm { chosen, .. } => {
            (&chosen.call.reflex, chosen.judged.as_ref()?)
        }
        Decision::Ask { asking, .. } => (&asking.reflex, &asking.judged),
    };
    Some((
        reflex,
        judged
            .judgments()
            .iter()
            .map(|judgment| judgment.question.clone())
            .collect(),
    ))
}

/// A value of the argument's own kind, to answer an ask with.
fn answer(reflex: &str, argument: &str) -> Value {
    match (reflex, argument) {
        ("lights", "room") => Value::Word {
            word: Word::new("den").unwrap(),
            value: None,
        },
        ("lights", "state") => Value::Option {
            key: OptionKey::new("on").unwrap(),
        },
        ("lights", "brightness") => pick("50", 0, 2, PickValue::Number { value: 50.0 }),
        ("timer", "duration") => pick("10 minutes", 0, 10, PickValue::Seconds { value: 600 }),
        ("timer", "label") => pick(
            "\"eggs\"",
            1,
            5,
            PickValue::Quoted {
                value: Clean::new("eggs").unwrap(),
            },
        ),
        _ => unreachable!("the fixture plan has no other argument"),
    }
}

proptest! {
    #[test]
    fn raising_a_floor_never_moves_an_outcome_toward_run(
        reading in reading(),
        (lower, higher) in a_gate().prop_flat_map(|gate| (Just(gate), raised(gate))),
    ) {
        let plan = plan();
        let before = outcome(&gate(&plan, reading.clone(), Some(&lower)));
        let after = outcome(&gate(&plan, reading, Some(&higher)));
        let allowed: &[&str] = match before {
            "abstain" => &["abstain"],
            "confirm" => &["confirm", "abstain"],
            "ask" => &["ask", "abstain"],
            _ => &["run", "confirm", "abstain"],
        };
        prop_assert!(allowed.contains(&after), "{before} under {lower:?} became {after} under {higher:?}");
    }

    #[test]
    fn read_is_refused_above_write(route in prob(), read in prob(), write in prob()) {
        prop_assert_eq!(Gate::new(p(route), None, p(read), p(write)).is_ok(), read <= write);
    }

    #[test]
    fn a_destructive_winner_never_runs(reading in reading(), floors in a_gate()) {
        let plan = destructive_plan();
        if reading.winner.as_ref().map(|winner| winner.reflex.as_str()) == Some("lights") {
            prop_assert_ne!(outcome(&gate(&plan, reading.clone(), Some(&floors))), "run");
        }
        // Without a gate, nothing runs on its own.
        prop_assert_ne!(outcome(&gate(&plan, reading, None)), "run");
    }

    #[test]
    fn the_confidence_is_the_weakest_judgment(reading in reading()) {
        let judged = Judged::of(&reading).unwrap();
        let weakest = reading
            .judgments
            .iter()
            .map(|judgment| judgment.p)
            .min_by(|a, b| a.get().total_cmp(&b.get()))
            .unwrap();
        prop_assert_eq!(judged.confidence(), weakest);
        prop_assert_eq!(judged.weakest().p, weakest);
        prop_assert!(reading.judgments.contains(judged.weakest()));
    }

    #[test]
    fn filling_a_subset_of_the_missing_keeps_the_route_and_drops_their_judgments(
        reading in reading(),
        floors in a_gate(),
        chosen in proptest::collection::vec(any::<bool>(), 3),
    ) {
        let plan = plan();
        let Decision::Ask { asking, missing } = gate(&plan, reading, Some(&floors)) else {
            return Ok(());
        };
        let reflex = asking.reflex.clone();
        let before: Vec<QuestionId> = asking.judged.judgments().iter().map(|j| j.question.clone()).collect();
        let given: IndexMap<ArgName, Value> = missing
            .iter()
            .zip(chosen.iter().cycle())
            .filter(|(_, chosen)| **chosen)
            .map(|(missing, _)| (missing.arg.clone(), answer(reflex.as_str(), missing.arg.as_str())))
            .collect();
        let dropped: Vec<QuestionId> = given
            .keys()
            .map(|arg| QuestionId::Arg(reflex.clone(), arg.clone()))
            .collect();
        let filled = fill(&plan, asking, given, Some(&floors));
        let (after_reflex, after) = rests_on(&filled).expect("a filled ask is about its reflex");
        prop_assert_eq!(after_reflex, &reflex);
        prop_assert!(after.contains(&QuestionId::Route));
        let expected: Vec<&QuestionId> = before.iter().filter(|q| !dropped.contains(q)).collect();
        prop_assert_eq!(after.iter().collect::<Vec<_>>(), expected);
    }
}
