//! What holds over inputs no one wrote: an overlay never changes a manifest's needs, whatever it words; a
//! declaration never widens itself, what one adds over another is what the other lacks, and a narrowing is
//! within both. Generated by proptest and shrunk; a failure's seed lands in `proptest-regressions/`.

use std::fmt::Write as _;

use evoke_core::document::Text;
use evoke_core::name::LocalName;
use evoke_core::needs::{self, Entry, Hosts, Needs, Program};
use evoke_core::{Document, File, effective, manifest, overlay};
use proptest::prelude::*;

/// An entry from a small alphabet, so two declarations share and differ.
fn entry() -> impl Strategy<Value = Entry> {
    prop_oneof![
        Just(Entry::parse("~/Downloads").unwrap()),
        Just(Entry::parse("~/notes").unwrap()),
        Just(Entry::parse("/etc/hosts").unwrap()),
        Just(Entry::parse("/tmp/out").unwrap()),
        Just(Entry::parse("{to}").unwrap()),
        Just(Entry::parse("{file}").unwrap()),
    ]
}

fn program() -> impl Strategy<Value = Program> {
    prop_oneof![
        Just(Program::new("open").unwrap()),
        Just(Program::new("plutil").unwrap()),
        Just(Program::new("/usr/bin/env").unwrap()),
    ]
}

/// A declaration: each list a set from the alphabet, in any order.
fn needs() -> impl Strategy<Value = Needs> {
    (
        proptest::collection::vec(entry(), 0..4),
        proptest::collection::vec(entry(), 0..4),
        any::<bool>(),
        proptest::collection::vec(program(), 0..3),
    )
        .prop_map(|(reads, writes, any, runs)| Needs {
            reads: distinct(reads),
            writes: distinct(writes),
            hosts: if any { Hosts::Any } else { Hosts::None },
            runs: distinct(runs),
        })
}

fn distinct<T: PartialEq>(items: Vec<T>) -> Vec<T> {
    let mut kept: Vec<T> = Vec::new();
    for item in items {
        if !kept.contains(&item) {
            kept.push(item);
        }
    }
    kept
}

/// A manifest with a declaration, and an overlay of wording over it: a description, an effect that only
/// tightens, a new ask, a rewording of one option, examples and tests.
fn manifest_and_overlay() -> impl Strategy<Value = (String, String)> {
    (
        needs(),
        prop_oneof![Just("write"), Just("destructive")],
        proptest::option::of("[a-z][a-z ]{0,19}"),
        any::<bool>(),
        proptest::option::of("[a-z][a-z ]{0,11}"),
        proptest::option::of("[a-z][a-z ]{0,11}"),
        any::<bool>(),
    )
        .prop_map(|(needs, effect, description, tighten, ask, off, example)| {
            let mut manifest = String::from(
                "reflex = 1\ndescription = \"Lights.\"\neffect = \"write\"\nconfirm = \"Lights {state}?\"\nrun = \"lights.mts\"\n\n[config]\nfile = \"A file\"\n\n[args.state]\nask = \"What?\"\noptions = { on = \"On.\", off = \"Off.\" }\n\n[args.to]\nask = \"Where?\"\nvocab = \"places\"\noptional = true\n\n[examples]\n\"lights off\" = { state = \"off\" }\n",
            );
            if !needs.is_none() {
                let list = |entries: &[Entry]| {
                    entries
                        .iter()
                        .map(|entry| format!("\"{entry}\""))
                        .collect::<Vec<_>>()
                        .join(", ")
                };
                manifest.push_str("\n[needs]\n");
                if !needs.reads.is_empty() {
                    let _ = writeln!(manifest, "reads = [{}]", list(&needs.reads));
                }
                if !needs.writes.is_empty() {
                    let _ = writeln!(manifest, "writes = [{}]", list(&needs.writes));
                }
                if needs.hosts == Hosts::Any {
                    manifest.push_str("hosts = [\"*\"]\n");
                }
                if !needs.runs.is_empty() {
                    let programs: Vec<String> =
                        needs.runs.iter().map(|program| format!("\"{program}\"")).collect();
                    let _ = writeln!(manifest, "runs = [{}]", programs.join(", "));
                }
            }
            let mut yours = String::new();
            if let Some(description) = description {
                let _ = writeln!(yours, "description = \"{description}\"");
            }
            if tighten {
                let _ = writeln!(yours, "effect = \"{effect}\"");
            }
            if ask.is_some() || off.is_some() {
                yours.push_str("\n[args.state]\n");
                if let Some(ask) = ask {
                    let _ = writeln!(yours, "ask = \"{ask}\"");
                }
                if let Some(off) = off {
                    let _ = writeln!(yours, "options.off = \"{off}\"");
                }
            }
            if example {
                yours.push_str("\n[examples]\n\"kill the lights\" = { state = \"off\" }\n\n[tests]\n\"light a candle\" = false\n");
            }
            (manifest, yours)
        })
}

fn parse(text: &str) -> evoke_core::Manifest {
    manifest(Document {
        file: File::Manifest {
            name: LocalName::new("lights").unwrap(),
        },
        text: Text::Toml(text),
    })
    .expect("a generated manifest reads")
}

proptest! {
    #[test]
    fn an_overlay_never_changes_the_needs((shipped, yours) in manifest_and_overlay()) {
        let shipped = parse(&shipped);
        let yours = overlay(
            Document {
                file: File::Overlay { name: LocalName::new("lights").unwrap() },
                text: Text::Toml(&yours),
            },
            &shipped,
        )
        .expect("a generated overlay reads");
        prop_assert_eq!(&effective(&shipped, Some(&yours)).manifest.needs, &shipped.needs);
        prop_assert_eq!(&effective(&shipped, None).manifest.needs, &shipped.needs);
    }

    #[test]
    fn a_declaration_never_widens_itself_and_what_is_added_is_what_the_other_lacks(a in needs(), b in needs()) {
        prop_assert!(!needs::widens(&a, &a));
        let added = needs::added(&b, &a);
        prop_assert_eq!(needs::widens(&a, &b), !added.is_none());
        for entry in &added.reads {
            prop_assert!(b.reads.contains(entry) && !a.reads.contains(entry));
        }
        for entry in &added.writes {
            prop_assert!(b.writes.contains(entry) && !a.writes.contains(entry));
        }
        for program in &added.runs {
            prop_assert!(b.runs.contains(program) && !a.runs.contains(program));
        }
        prop_assert_eq!(added.hosts == Hosts::Any, b.hosts == Hosts::Any && a.hosts == Hosts::None);
    }

    #[test]
    fn a_narrowing_is_within_both_and_never_widens_either(shipped in needs(), consented in needs()) {
        let narrowed = needs::narrowed(&shipped, &consented);
        prop_assert!(!needs::widens(&shipped, &narrowed));
        prop_assert!(!needs::widens(&consented, &narrowed));
        prop_assert_eq!(needs::narrowed(&shipped, &shipped), shipped.clone());
        prop_assert!(needs::narrowed(&shipped, &Needs::default()).is_none());
    }

    #[test]
    fn consent_records_no_more_than_was_consented_to(locked in needs(), upstream in needs()) {
        let kept = match needs::consent(&locked, &upstream) {
            needs::Consent::Kept { needs } => needs,
            needs::Consent::Tightened { needs, removed } => {
                prop_assert_eq!(needs::added(&locked, &needs), removed);
                needs
            }
            needs::Consent::NeedsAccept { locked: kept, upstream: declared } => {
                prop_assert_eq!(&declared, &upstream);
                prop_assert!(needs::widens(&locked, &upstream));
                kept
            }
        };
        prop_assert!(!needs::widens(&locked, &kept));
        prop_assert!(!needs::widens(&upstream, &kept));
    }
}
